@name('get location')
GET http://127.0.0.1:8787/
"Authorization" : "Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IkIwU0U0Q2xIME1nSjdDNmYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3FzcWVnYXppZW1rcG5kaWJ1YXV4LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJjYTE1YTZlNy1mMjg2LTQ2YWItYTM5Ni01ZDljNzYwNDliZWEiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzU1MjM0NTczLCJpYXQiOjE3NTUyMzA5NzMsImVtYWlsIjoiY2FybGl0b3NudTQxQGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzU1MjMwOTczfV0sInNlc3Npb25faWQiOiIwMWM2YjE2NC1hY2EzLTRmNTMtOWRlNS02NDQ4ZTcyNjdjY2EiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.2vzM5Z8m65Hsvq20Kntto45y4Rz6U2lHq0OfeQKO1QQ"

@name('update location')
PATCH http://127.0.0.1:8787/
"Content-Type" : "application/json"
"Authorization" : "Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IkIwU0U0Q2xIME1nSjdDNmYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3FzcWVnYXppZW1rcG5kaWJ1YXV4LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJjYTE1YTZlNy1mMjg2LTQ2YWItYTM5Ni01ZDljNzYwNDliZWEiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzU1MjM0NTczLCJpYXQiOjE3NTUyMzA5NzMsImVtYWlsIjoiY2FybGl0b3NudTQxQGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzU1MjMwOTczfV0sInNlc3Npb25faWQiOiIwMWM2YjE2NC1hY2EzLTRmNTMtOWRlNS02NDQ4ZTcyNjdjY2EiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.2vzM5Z8m65Hsvq20Kntto45y4Rz6U2lHq0OfeQKO1QQ"
data('{
    "x": -103.3334,
    "y": 20.6076
}')